# Main background
theme[main_bg]="{{background}}"

# Main text color
theme[main_fg]="{{foreground}}"

# Title color for boxes
theme[title]="{{foreground}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{color4}}"

# Background color of selected items
theme[selected_bg]="{{color2}}"

# Foreground color of selected items
theme[selected_fg]="{{foreground}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{color8}}"

# Color of text appearing on top of graphs
theme[graph_text]="{{color7}}"

# Background color of the meter bar
theme[meter_bg]="{{color8}}"

# Misc colors for processes box
theme[proc_misc]="{{color4}}"

# CPU box outline color
theme[cpu_box]="{{color2}}"

# Memory/disks box outline color
theme[mem_box]="{{color3}}"

# Net box outline color
theme[net_box]="{{color5}}"

# Processes box outline color
theme[proc_box]="{{color1}}"

# Box divider line and target runtime
theme[div_line]="{{color8}}"

# Temperature graph colors
theme[temp_start]="{{color2}}"
theme[temp_mid]="{{color3}}"
theme[temp_end]="{{color1}}"

# CPU graph colors
theme[cpu_start]="{{color2}}"
theme[cpu_mid]="{{color4}}"
theme[cpu_end]="{{color1}}"

# Mem/Disk free meter
theme[free_start]="{{color2}}"
theme[free_mid]="{{color3}}"
theme[free_end]="{{color5}}"

# Mem/Disk cached meter
theme[cached_start]="{{color4}}"
theme[cached_mid]="{{color5}}"
theme[cached_end]="{{color6}}"

# Mem/Disk available meter
theme[available_start]="{{color2}}"
theme[available_mid]="{{color3}}"
theme[available_end]="{{color4}}"

# Mem/Disk used meter
theme[used_start]="{{color3}}"
theme[used_mid]="{{color5}}"
theme[used_end]="{{color1}}"

# Download graph colors
theme[download_start]="{{color2}}"
theme[download_mid]="{{color4}}"
theme[download_end]="{{color6}}"

# Upload graph colors
theme[upload_start]="{{color3}}"
theme[upload_mid]="{{color5}}"
theme[upload_end]="{{color1}}"

# Process sorting and tree
theme[process_start]="{{color2}}"
theme[process_mid]="{{color4}}"
theme[process_end]="{{color1}}"
