# Fallback colors to prevent parsing errors when wallust truncates its template
$background = rgb(000000)
$color2 = rgb(111111)
$color4 = rgb(222222)

# Wallust Colors
source = ~/.cache/wallust/colors-hyprland.conf

# Split Config
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
