-- wallust.lua — Neovim colorscheme driven by wallust-generated colors
vim.cmd("hi clear")
vim.g.colors_name = "wallust"

local ok, c = pcall(dofile, vim.fn.expand("~/.cache/wallust/colors-nvim.lua"))
if not ok then
    vim.notify("wallust: colors not generated yet, run `wallust run` first", vim.log.levels.WARN)
    return
end

local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

-- Editor
hi("Normal",       { fg = c.foreground, bg = "NONE" })
hi("NormalFloat",  { fg = c.foreground, bg = c.color0 })
hi("FloatBorder",  { fg = c.color8,     bg = c.color0 })
hi("CursorLine",   { bg = c.color0 })
hi("CursorLineNr", { fg = c.color4,     bold = true })
hi("LineNr",       { fg = c.color8 })
hi("SignColumn",   { bg = "NONE" })
hi("ColorColumn",  { bg = c.color0 })
hi("Visual",       { bg = c.color8 })
hi("IncSearch",    { fg = c.background, bg = c.color3 })
hi("Search",       { fg = c.background, bg = c.color6 })
hi("MatchParen",   { fg = c.color3,     bold = true, underline = true })

-- Popup menu
hi("Pmenu",        { fg = c.foreground, bg = c.color0 })
hi("PmenuSel",     { fg = c.background, bg = c.color4 })
hi("PmenuSbar",    { bg = c.color0 })
hi("PmenuThumb",   { bg = c.color8 })

-- Split / status
hi("VertSplit",    { fg = c.color8 })
hi("StatusLine",   { fg = c.foreground, bg = c.color0 })
hi("StatusLineNC", { fg = c.color8,     bg = c.color0 })
hi("WinSeparator", { fg = c.color8 })

-- Tabs
hi("TabLine",      { fg = c.color8,     bg = c.color0 })
hi("TabLineFill",  { bg = c.color0 })
hi("TabLineSel",   { fg = c.foreground, bg = c.background })

-- Messages
hi("ErrorMsg",     { fg = c.color1 })
hi("WarningMsg",   { fg = c.color3 })
hi("ModeMsg",      { fg = c.color2, bold = true })
hi("MoreMsg",      { fg = c.color6 })
hi("Question",     { fg = c.color6 })
hi("Title",        { fg = c.color4, bold = true })
hi("NonText",      { fg = c.color8 })
hi("SpecialKey",   { fg = c.color8 })
hi("Folded",       { fg = c.color8, bg = c.color0 })
hi("FoldColumn",   { fg = c.color8, bg = c.background })
hi("Directory",    { fg = c.color4 })

-- Diff
hi("DiffAdd",      { fg = c.color2, bg = c.background })
hi("DiffChange",   { fg = c.color3, bg = c.background })
hi("DiffDelete",   { fg = c.color1, bg = c.background })
hi("DiffText",     { fg = c.color3, bg = c.color0, bold = true })

-- Syntax
hi("Comment",      { fg = c.color8, italic = true })
hi("Constant",     { fg = c.color5 })
hi("String",       { fg = c.color2 })
hi("Character",    { fg = c.color2 })
hi("Number",       { fg = c.color5 })
hi("Boolean",      { fg = c.color5 })
hi("Float",        { fg = c.color5 })
hi("Identifier",   { fg = c.color4 })
hi("Function",     { fg = c.color6 })
hi("Statement",    { fg = c.color1 })
hi("Conditional",  { fg = c.color1 })
hi("Repeat",       { fg = c.color1 })
hi("Label",        { fg = c.color1 })
hi("Operator",     { fg = c.foreground })
hi("Keyword",      { fg = c.color5 })
hi("Exception",    { fg = c.color1 })
hi("PreProc",      { fg = c.color3 })
hi("Include",      { fg = c.color4 })
hi("Define",       { fg = c.color5 })
hi("Macro",        { fg = c.color5 })
hi("PreCondit",    { fg = c.color3 })
hi("Type",         { fg = c.color3 })
hi("StorageClass", { fg = c.color3 })
hi("Structure",    { fg = c.color3 })
hi("Typedef",      { fg = c.color3 })
hi("Special",      { fg = c.color6 })
hi("SpecialChar",  { fg = c.color6 })
hi("Tag",          { fg = c.color4 })
hi("Delimiter",    { fg = c.foreground })
hi("Debug",        { fg = c.color1 })
hi("Underlined",   { fg = c.color4, underline = true })
hi("Error",        { fg = c.color1, bold = true })
hi("Todo",         { fg = c.color3, bg = c.color0, bold = true })

-- Treesitter
hi("@variable",            { fg = c.foreground })
hi("@variable.builtin",    { fg = c.color5 })
hi("@constant",            { fg = c.color5 })
hi("@constant.builtin",    { fg = c.color5 })
hi("@function",            { fg = c.color6 })
hi("@function.builtin",    { fg = c.color6 })
hi("@function.call",       { fg = c.color6 })
hi("@method",              { fg = c.color6 })
hi("@method.call",         { fg = c.color6 })
hi("@keyword",             { fg = c.color5 })
hi("@keyword.function",    { fg = c.color5 })
hi("@keyword.return",      { fg = c.color1 })
hi("@keyword.operator",    { fg = c.color1 })
hi("@string",              { fg = c.color2 })
hi("@string.escape",       { fg = c.color6 })
hi("@number",              { fg = c.color5 })
hi("@boolean",             { fg = c.color5 })
hi("@type",                { fg = c.color3 })
hi("@type.builtin",        { fg = c.color3 })
hi("@property",            { fg = c.color4 })
hi("@field",               { fg = c.color4 })
hi("@parameter",           { fg = c.foreground })
hi("@punctuation.bracket",  { fg = c.foreground })
hi("@punctuation.delimiter",{ fg = c.foreground })
hi("@comment",             { fg = c.color8, italic = true })
hi("@tag",                 { fg = c.color1 })
hi("@tag.attribute",       { fg = c.color3 })
hi("@tag.delimiter",       { fg = c.foreground })
hi("@constructor",         { fg = c.color3 })
hi("@operator",            { fg = c.foreground })
hi("@namespace",           { fg = c.color4 })

-- Diagnostics
hi("DiagnosticError",      { fg = c.color1 })
hi("DiagnosticWarn",       { fg = c.color3 })
hi("DiagnosticInfo",       { fg = c.color4 })
hi("DiagnosticHint",       { fg = c.color6 })
hi("DiagnosticUnderlineError", { sp = c.color1, undercurl = true })
hi("DiagnosticUnderlineWarn",  { sp = c.color3, undercurl = true })
hi("DiagnosticUnderlineInfo",  { sp = c.color4, undercurl = true })
hi("DiagnosticUnderlineHint",  { sp = c.color6, undercurl = true })

-- Git signs
hi("GitSignsAdd",          { fg = c.color2 })
hi("GitSignsChange",       { fg = c.color3 })
hi("GitSignsDelete",       { fg = c.color1 })

-- Telescope
hi("TelescopeNormal",      { fg = c.foreground, bg = c.color0 })
hi("TelescopeBorder",      { fg = c.color8,     bg = c.color0 })
hi("TelescopePromptNormal", { fg = c.foreground, bg = c.color0 })
hi("TelescopePromptBorder", { fg = c.color4,     bg = c.color0 })
hi("TelescopePromptTitle",  { fg = c.background, bg = c.color4 })
hi("TelescopeResultsTitle", { fg = c.color0 })
hi("TelescopePreviewTitle", { fg = c.background, bg = c.color2 })
hi("TelescopeSelection",   { bg = c.color8 })
hi("TelescopeMatching",    { fg = c.color3, bold = true })
